import type { Assessment, CitationFindingCode, CitationSource } from '../contracts.js';

export type InlineCorpusCase = {
  readonly id: `F${string}`;
  readonly answer: string;
  readonly sources: readonly CitationSource[];
  readonly outcome: 'pass' | 'fail';
  readonly sourceCatalog: Assessment;
  readonly citationSyntax: Assessment;
  readonly sourceReference: Assessment;
  readonly citationCount: number;
  readonly findingCodes: readonly CitationFindingCode[];
};

export const INLINE_CORPUS: readonly InlineCorpusCase[] = [
  {
    id: 'F01',
    answer: 'Result [1].',
    sources: [{ id: '1' }],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'verified',
    sourceReference: 'verified',
    citationCount: 1,
    findingCodes: [],
  },
  {
    id: 'F02',
    answer: 'Result [1, 2].',
    sources: [{ id: '1' }, { id: '2' }],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'verified',
    sourceReference: 'verified',
    citationCount: 2,
    findingCodes: [],
  },
  {
    id: 'F03',
    answer: 'Result [@doc-a].',
    sources: [{ id: 'doc-a' }],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'verified',
    sourceReference: 'verified',
    citationCount: 1,
    findingCodes: [],
  },
  {
    id: 'F04',
    answer: 'Result [99].',
    sources: [],
    outcome: 'fail',
    sourceCatalog: 'verified',
    citationSyntax: 'verified',
    sourceReference: 'failed',
    citationCount: 1,
    findingCodes: ['CITATION_SOURCE_UNKNOWN'],
  },
  {
    id: 'F05',
    answer: 'Result [@missing].',
    sources: [],
    outcome: 'fail',
    sourceCatalog: 'verified',
    citationSyntax: 'verified',
    sourceReference: 'failed',
    citationCount: 1,
    findingCodes: ['CITATION_SOURCE_UNKNOWN'],
  },
  {
    id: 'F06',
    answer: 'Status [draft].',
    sources: [],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'not-assessed',
    sourceReference: 'not-assessed',
    citationCount: 0,
    findingCodes: [],
  },
  {
    id: 'F07',
    answer: '[manual](https://example.test)',
    sources: [],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'not-assessed',
    sourceReference: 'not-assessed',
    citationCount: 0,
    findingCodes: [],
  },
  {
    id: 'F08',
    answer: '`value[1]`',
    sources: [],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'not-assessed',
    sourceReference: 'not-assessed',
    citationCount: 0,
    findingCodes: [],
  },
  {
    id: 'F09',
    answer: '```txt\nvalue [1]\n```',
    sources: [],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'not-assessed',
    sourceReference: 'not-assessed',
    citationCount: 0,
    findingCodes: [],
  },
  {
    id: 'F10',
    answer: '\\[1]',
    sources: [],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'not-assessed',
    sourceReference: 'not-assessed',
    citationCount: 0,
    findingCodes: [],
  },
  {
    id: 'F11',
    answer: 'Result [1,].',
    sources: [{ id: '1' }],
    outcome: 'fail',
    sourceCatalog: 'verified',
    citationSyntax: 'failed',
    sourceReference: 'not-assessed',
    citationCount: 0,
    findingCodes: ['CITATION_MALFORMED'],
  },
  {
    id: 'F12',
    answer: 'Result [1, 1].',
    sources: [{ id: '1' }],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'verified',
    sourceReference: 'verified',
    citationCount: 2,
    findingCodes: ['CITATION_DUPLICATE_IN_GROUP'],
  },
  {
    id: 'F13',
    answer: 'First [1], then [1].',
    sources: [{ id: '1' }],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'verified',
    sourceReference: 'verified',
    citationCount: 2,
    findingCodes: [],
  },
  {
    id: 'F14',
    answer: 'Result [1].',
    sources: [{ id: '1' }, { id: '1' }],
    outcome: 'fail',
    sourceCatalog: 'failed',
    citationSyntax: 'verified',
    sourceReference: 'verified',
    citationCount: 1,
    findingCodes: ['SOURCE_ID_DUPLICATE'],
  },
  {
    id: 'F15',
    answer: 'No citation.',
    sources: [{ id: 'bad id' }],
    outcome: 'fail',
    sourceCatalog: 'failed',
    citationSyntax: 'not-assessed',
    sourceReference: 'not-assessed',
    citationCount: 0,
    findingCodes: ['SOURCE_ID_INVALID'],
  },
  {
    id: 'F16',
    answer: 'Result [@__proto__].',
    sources: [{ id: '__proto__' }],
    outcome: 'pass',
    sourceCatalog: 'verified',
    citationSyntax: 'verified',
    sourceReference: 'verified',
    citationCount: 1,
    findingCodes: [],
  },
];
